/** Proyecto con NextJS y React (con aclaraciones) */

// Recurso que se utiliza para poder modificar el head de metadatos
import Head from 'next/head'

// Archivo css que se aplica SOLO sobre ese modulo
import styles from '../styles/Home.module.css'

// Importo el componente creado
import Navbar from '../components/Navbar'
//Aclaracion
/**Los estilos que apliquen de manera global se encuentran en el
 * archivo globals.css */

//Modificacion de la metadata y el retorno de la funcion
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Astro Queen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
    </div>
  )
}
